import os

from dotenv import load_dotenv

load_dotenv()

PROJECT_NAME = "Atlas"

ENVIRONMENT = os.getenv("ATLAS_ENV", "development")

FINANCIAL_API_KEY = os.getenv("FINANCIAL_API_KEY")

FINANCIAL_API_BASE_URL = os.getenv(
    "FINANCIAL_API_BASE_URL",
    "",
)

SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")

SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE", "ATLAS_DB")
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA", "ANALYTICS")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "ATLAS_WH")
